# Generated by Django 5.2.16 on 2026-07-19 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('capture_date', models.DateField()),
                ('source_format', models.CharField(blank=True, choices=[('las', 'Las'), ('laz', 'Laz')], max_length=8, null=True)),
                ('source_size_bytes', models.BigIntegerField()),
                ('source_key', models.CharField(max_length=512)),
                ('source_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project')),
            ],
            options={
                'ordering': ['capture_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('validation', 'Validation'), ('reprojection', 'Reprojection'), ('surface_generation', 'Surface Generation')], default='validation', max_length=32)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=64, null=True)),
                ('failure_message_key', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='surveys.survey')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tus_upload_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('declared_filename', models.CharField(max_length=255)),
                ('declared_size_bytes', models.BigIntegerField()),
                ('capture_date', models.DateField()),
                ('survey_name', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('dem', 'Dem'), ('hillshade', 'Hillshade'), ('copc', 'Copc')], max_length=16)),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('resolution_m', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='surveys.processingrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'kind'), name='artifact_kind_per_run_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='processingrun',
            constraint=models.UniqueConstraint(fields=('survey', 'number'), name='run_number_unique'),
        ),
    ]
