# Generated by Django 5.2.16 on 2026-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='tus_upload_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
