# Generated by Django 5.2.16 on 2026-07-20 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_uploadsession_tus_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedartifact',
            name='option_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='input_type',
            field=models.CharField(default='point_cloud', max_length=32),
        ),
        migrations.AddField(
            model_name='survey',
            name='input_type',
            field=models.CharField(default='point_cloud', max_length=32),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RunOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_id', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('reused', 'Reused')], default='pending', max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=64, null=True)),
                ('failure_message_key', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reused_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_by', to='surveys.processingrun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.processingrun')),
            ],
            options={
                'ordering': ['option_id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'option_id'), name='run_option_unique')],
            },
        ),
    ]
